### ISSUE TITLE
How to generate gif hexadecimal file?

### ISSUE THREAD

**Issue by modi12jin** [VolosR/aNIMATIONS#1]
I want to know what tool to generate hexadecimal file

**Comment by VolosR** [comment]
https://drive.google.com/file/d/1f4f8cyS7F7k_L5foAa5kmLffE1aCQ4KB/view?usp=sharing


pet, 4. pro 2020. u 04:16 modi12jin <notifications@github.com> napisao je:

**Comment by VolosR** [comment]
Please, subscribe to my youtube channel! Tnx

pet, 4. pro 2020. u 09:56 Volos Projects <arduino.b2016@gmail.com> napisao
je:

**Comment by modi12jin** [comment]
Do gif files need to be processed into pictures in advance?  So what tools do you need to process into pictures?

**Comment by VolosR** [comment]
https://youtu.be/-h9Vm0Ow_Is here is whole tutorial, you havent seen video?

**Comment by modi12jin** [comment]
Just watched the video, thank you very much!
